#! /bin/bash

cd TaggedEMC
./Compile
./Clean
mv ALERT-TagEMC.pdf ..

cd ../TaggedDVCS
./Compile
./Clean
mv ALERT-TagDVCS.pdf ..

cd ../NuclearGPD
./Compile
./Clean
mv ALERT-NuclGPDs.pdf ..

cd ../ExtraTopics
./Compile
./Clean
mv ALERT-4.pdf ..

#Add creation of a tar?
